# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'realize.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(736, 470)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pushButton_BB84 = QtGui.QPushButton(self.tab)
        self.pushButton_BB84.setGeometry(QtCore.QRect(580, 350, 91, 51))
        self.pushButton_BB84.setObjectName(_fromUtf8("pushButton_BB84"))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 71, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(30, 240, 91, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_BB84_ch1_fre = QtGui.QLineEdit(self.tab)
        self.lineEdit_BB84_ch1_fre.setGeometry(QtCore.QRect(130, 240, 131, 31))
        self.lineEdit_BB84_ch1_fre.setObjectName(_fromUtf8("lineEdit_BB84_ch1_fre"))
        self.lineEdit_BB84_ch2_fre = QtGui.QLineEdit(self.tab)
        self.lineEdit_BB84_ch2_fre.setGeometry(QtCore.QRect(130, 300, 131, 31))
        self.lineEdit_BB84_ch2_fre.setObjectName(_fromUtf8("lineEdit_BB84_ch2_fre"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(30, 300, 91, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(310, 300, 91, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(310, 240, 91, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_BB84_ch2_t = QtGui.QLineEdit(self.tab)
        self.lineEdit_BB84_ch2_t.setGeometry(QtCore.QRect(410, 300, 131, 31))
        self.lineEdit_BB84_ch2_t.setObjectName(_fromUtf8("lineEdit_BB84_ch2_t"))
        self.lineEdit_BB84_ch1_t = QtGui.QLineEdit(self.tab)
        self.lineEdit_BB84_ch1_t.setGeometry(QtCore.QRect(410, 240, 131, 31))
        self.lineEdit_BB84_ch1_t.setObjectName(_fromUtf8("lineEdit_BB84_ch1_t"))
        self.textBrowser_BB84_show = QtGui.QTextBrowser(self.tab)
        self.textBrowser_BB84_show.setGeometry(QtCore.QRect(120, 20, 351, 201))
        self.textBrowser_BB84_show.setObjectName(_fromUtf8("textBrowser_BB84_show"))
        self.pushButton_BB84_fre = QtGui.QPushButton(self.tab)
        self.pushButton_BB84_fre.setGeometry(QtCore.QRect(170, 350, 91, 31))
        self.pushButton_BB84_fre.setObjectName(_fromUtf8("pushButton_BB84_fre"))
        self.pushButton_BB84_t = QtGui.QPushButton(self.tab)
        self.pushButton_BB84_t.setGeometry(QtCore.QRect(450, 350, 91, 31))
        self.pushButton_BB84_t.setObjectName(_fromUtf8("pushButton_BB84_t"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.pushButton_COW = QtGui.QPushButton(self.tab_3)
        self.pushButton_COW.setGeometry(QtCore.QRect(580, 350, 91, 51))
        self.pushButton_COW.setObjectName(_fromUtf8("pushButton_COW"))
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(310, 240, 91, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 240, 91, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_COW_ch1_t = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_COW_ch1_t.setGeometry(QtCore.QRect(410, 240, 131, 31))
        self.lineEdit_COW_ch1_t.setObjectName(_fromUtf8("lineEdit_COW_ch1_t"))
        self.lineEdit_COW_ch1_fre = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_COW_ch1_fre.setGeometry(QtCore.QRect(130, 240, 131, 31))
        self.lineEdit_COW_ch1_fre.setObjectName(_fromUtf8("lineEdit_COW_ch1_fre"))
        self.label_15 = QtGui.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(40, 31, 71, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.textBrowser_COW_show = QtGui.QTextBrowser(self.tab_3)
        self.textBrowser_COW_show.setGeometry(QtCore.QRect(120, 20, 351, 201))
        self.textBrowser_COW_show.setObjectName(_fromUtf8("textBrowser_COW_show"))
        self.pushButton_COW_fre = QtGui.QPushButton(self.tab_3)
        self.pushButton_COW_fre.setGeometry(QtCore.QRect(170, 300, 91, 31))
        self.pushButton_COW_fre.setObjectName(_fromUtf8("pushButton_COW_fre"))
        self.pushButton_COW_t = QtGui.QPushButton(self.tab_3)
        self.pushButton_COW_t.setGeometry(QtCore.QRect(450, 300, 91, 31))
        self.pushButton_COW_t.setObjectName(_fromUtf8("pushButton_COW_t"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lineEdit_att_set_1 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_att_set_1.setGeometry(QtCore.QRect(480, 230, 111, 31))
        self.lineEdit_att_set_1.setObjectName(_fromUtf8("lineEdit_att_set_1"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(350, 230, 131, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_att_t = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_att_t.setGeometry(QtCore.QRect(140, 350, 111, 31))
        self.lineEdit_att_t.setObjectName(_fromUtf8("lineEdit_att_t"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(20, 350, 101, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_sig_t = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_sig_t.setGeometry(QtCore.QRect(480, 350, 111, 31))
        self.lineEdit_sig_t.setObjectName(_fromUtf8("lineEdit_sig_t"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(370, 350, 111, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.textBrowser_other_show = QtGui.QTextBrowser(self.tab_2)
        self.textBrowser_other_show.setGeometry(QtCore.QRect(120, 20, 381, 181))
        self.textBrowser_other_show.setObjectName(_fromUtf8("textBrowser_other_show"))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(40, 30, 71, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.pushButton_att_set_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_att_set_2.setGeometry(QtCore.QRect(600, 280, 81, 31))
        self.pushButton_att_set_2.setObjectName(_fromUtf8("pushButton_att_set_2"))
        self.lineEdit_att_insertloss_1_show = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_att_insertloss_1_show.setGeometry(QtCore.QRect(140, 230, 111, 31))
        self.lineEdit_att_insertloss_1_show.setObjectName(_fromUtf8("lineEdit_att_insertloss_1_show"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 121, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_att_insertloss_2_show = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_att_insertloss_2_show.setGeometry(QtCore.QRect(140, 280, 111, 31))
        self.lineEdit_att_insertloss_2_show.setObjectName(_fromUtf8("lineEdit_att_insertloss_2_show"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 280, 121, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_att_set_2 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_att_set_2.setGeometry(QtCore.QRect(480, 280, 111, 31))
        self.lineEdit_att_set_2.setObjectName(_fromUtf8("lineEdit_att_set_2"))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(350, 280, 131, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.pushButton_insertloss_set_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_insertloss_set_2.setGeometry(QtCore.QRect(260, 280, 81, 31))
        self.pushButton_insertloss_set_2.setObjectName(_fromUtf8("pushButton_insertloss_set_2"))
        self.pushButton_att_t = QtGui.QPushButton(self.tab_2)
        self.pushButton_att_t.setGeometry(QtCore.QRect(260, 350, 81, 31))
        self.pushButton_att_t.setObjectName(_fromUtf8("pushButton_att_t"))
        self.pushButton_sig_t = QtGui.QPushButton(self.tab_2)
        self.pushButton_sig_t.setGeometry(QtCore.QRect(600, 350, 91, 31))
        self.pushButton_sig_t.setObjectName(_fromUtf8("pushButton_sig_t"))
        self.pushButton_insertloss_set_1 = QtGui.QPushButton(self.tab_2)
        self.pushButton_insertloss_set_1.setGeometry(QtCore.QRect(260, 230, 81, 31))
        self.pushButton_insertloss_set_1.setObjectName(_fromUtf8("pushButton_insertloss_set_1"))
        self.pushButton_att_set_1 = QtGui.QPushButton(self.tab_2)
        self.pushButton_att_set_1.setGeometry(QtCore.QRect(600, 230, 81, 31))
        self.pushButton_att_set_1.setObjectName(_fromUtf8("pushButton_att_set_1"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.pushButton_BB84.setText(_translate("Form", "运行", None))
        self.label_6.setText(_translate("Form", "加载信息窗口", None))
        self.label_7.setText(_translate("Form", "CH1实时频率显示", None))
        self.label_8.setText(_translate("Form", "CH2实时频率显示", None))
        self.label_9.setText(_translate("Form", "CH2实时温度显示", None))
        self.label_10.setText(_translate("Form", "CH1实时温度显示", None))
        self.pushButton_BB84_fre.setText(_translate("Form", "频率查询", None))
        self.pushButton_BB84_t.setText(_translate("Form", "温度查询", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "BB84", None))
        self.pushButton_COW.setText(_translate("Form", "运行", None))
        self.label_11.setText(_translate("Form", "CH1实时温度显示", None))
        self.label_13.setText(_translate("Form", "CH1实时频率显示", None))
        self.label_15.setText(_translate("Form", "加载信息窗口", None))
        self.pushButton_COW_fre.setText(_translate("Form", "频率查询", None))
        self.pushButton_COW_t.setText(_translate("Form", "温度查询", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "COW", None))
        self.label.setText(_translate("Form", "衰减模块CH1衰减值设置", None))
        self.label_2.setText(_translate("Form", " 衰减模块温度监测", None))
        self.label_4.setText(_translate("Form", "信号源模块温度监测", None))
        self.label_16.setText(_translate("Form", "加载信息窗口", None))
        self.pushButton_att_set_2.setText(_translate("Form", "CH2衰减设置", None))
        self.lineEdit_att_insertloss_1_show.setText(_translate("Form", "插损值无效", None))
        self.label_12.setText(_translate("Form", "衰减模块CH1插损设置", None))
        self.lineEdit_att_insertloss_2_show.setText(_translate("Form", "插损值无效", None))
        self.label_14.setText(_translate("Form", "衰减模块CH2插损设置", None))
        self.label_5.setText(_translate("Form", "衰减模块CH2衰减值设置", None))
        self.pushButton_insertloss_set_2.setText(_translate("Form", "无效勿点", None))
        self.pushButton_att_t.setText(_translate("Form", "衰减温度查询", None))
        self.pushButton_sig_t.setText(_translate("Form", "信号源温度查询", None))
        self.pushButton_insertloss_set_1.setText(_translate("Form", "无效勿点", None))
        self.pushButton_att_set_1.setText(_translate("Form", "CH1衰减设置", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "其他参数", None))
if __name__ == "__main__":
    import sys

    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
